using DHOG_WPF.DataAccess;
using Telerik.Windows.Controls;
using Telerik.Windows.Controls.GridView;
using System.Windows.Controls;
using System.Windows.Media;

namespace DHOG_WPF.Views
{
    public class SimpleDataGridView : RadGridView
    {
        int contador = 0;
        public void BaseDataGrid_Formating(object sender, RowLoadedEventArgs e)
        {

            contador = contador + 1;
            System.Type Tipo = e.Row.Cells.GetType();

            if ((contador % 2) == 0)
                e.Row.Background = new SolidColorBrush(Colors.LightGray);
            else
                e.Row.Background = new SolidColorBrush(Colors.WhiteSmoke);


            bool Valor;
            Valor = Tipo.IsValueType;

            if (Valor)
            {
                e.Row.Cells.ToString();
                //        column.DataFormatString = "{0:F0}";

            }

        }



        public SimpleDataGridView(string table, bool HasFewColumns,int tipo)
        {
            ItemsSource = ResultsReader.GetResultsFromTable(table);
            if (tipo!= 0)
            {
                if (string.IsNullOrEmpty(table)) return;
            IsReadOnly = false;
            if (HasFewColumns)
                ColumnWidth = new GridViewLength(1, GridViewLengthUnitType.Star);

            

            ClipboardCopyMode = GridViewClipboardCopyMode.Cells;
            SelectionUnit = GridViewSelectionUnit.Mixed;
            SelectionMode = SelectionMode.Extended;
            GroupPanelBackground = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFE6E6E6"));
            GroupPanelForeground = new SolidColorBrush(Colors.Black);
            FilteringMode = Telerik.Windows.Controls.GridView.FilteringMode.Popup;
            RowLoaded += BaseDataGrid_Formating;

            for (int i = 1; i < Columns.Count; i++)
            {
                GridViewDataColumn column = Columns[i] as GridViewDataColumn;
                column.ShowFieldFilters = false;
                column.ShowFilterButton = false;
                System.Type Tipo = column.DataType;
                bool Valor;
                Valor = Tipo.IsValueType;

                    if (Valor)
                    {
                        if (column.Header.ToString().ToLower() == "escenario" ||
                            column.Header.ToString().ToLower() == "bloque" ||
                            column.Header.ToString().ToLower() == "periodo")
                        {
                            column.DataFormatString = "{0:F0}";
                        }
                        else
                        {
                            column.DataFormatString = "{0:F2}";
                        }
                    }

                }
            GridViewDataColumn textBoxColumn = new GridViewDataColumn();
            textBoxColumn = new GridViewDataColumn
            {
                Name = "FechaPeriodo",
                Header = "Fecha",
                IsAutoGenerated = true,
                Width = 80
            };
        }
        }
    }
}
